version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: template_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
